### ISSUE TITLE
Is there RGB Data in the Dataset Release?

### ISSUE THREAD

**Issue by Bacon9629** [QiWang233/DailyDVS-200#3]
Hello, I noticed that the paper mentioned using both RGB cameras and event cameras for data collection. However, after downloading the dataset, I only found event data. 
Will the RGB data be released as well?

**Comment by QiWang233** [comment]
Thank you for your inquiry regarding the RGB data associated with the DailyDVS-200 dataset.

I would like to clarify that the RGB and event data collected for our study were not synchronized between the cameras. Due to the differences in the data acquisition processes and the challenges in aligning the data from these two distinct types of cameras, we have decided not to release the RGB data.

However, if you have specific research or application needs that require the RGB data, we would be interested in learning more about your intended use. Could you please elaborate on the purpose and how the RGB data would contribute to your project? This information might help us consider if there is a possibility to provide the RGB data or suggest alternative solutions that could be beneficial for your work.

**Comment by Bacon9629** [comment]
Thank you for your response!
I will organize the information on my end first, and I will get back to you once it's completed.

**Comment by Mahmoud-Ali-FCIS** [comment]
Hello @QiWang233 ,
Thank you for providing your valuable dataset. I am particularly interested in the RGB data. 

I am currently working on skeleton-based action recognition, and access to your RGB data (to extract the skeleton data) would greatly support my research by enabling me to evaluate the generalization and transferability of my model.

If releasing the raw RGB videos is not possible due to privacy concerns, would it be feasible to extract the skeleton data from the videos and share that instead?

Thank you for your consideration.
